//! Query scenario corpus (v0.0.268).
//!
//! 100+ real-world queries for comprehensive testing.

use crate::teams::Team;
use serde::{Deserialize, Serialize};

/// Query difficulty level
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Difficulty {
    /// Simple lookup, fast path eligible
    Simple,
    /// Needs probe + single specialist
    Medium,
    /// May need escalation or multiple probes
    Complex,
}

/// Expected resolution path
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExpectedPath {
    /// Should use fast path (no LLM)
    FastPath,
    /// Junior only (no escalation)
    JuniorOnly,
    /// Senior review likely
    SeniorReview,
    /// May need clarification
    Clarification,
    /// Recipe should be learned after success
    LearnableRecipe,
}

/// Single test scenario
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryScenario {
    pub id: u32,
    pub query: String,
    pub expected_team: Team,
    pub difficulty: Difficulty,
    pub expected_path: ExpectedPath,
    /// Similar query to test recipe recall
    pub similar_query: Option<String>,
    pub tags: Vec<String>,
}

/// Full corpus of test scenarios
pub struct ScenarioCorpus {
    pub scenarios: Vec<QueryScenario>,
}

impl ScenarioCorpus {
    pub fn load() -> Self {
        Self {
            scenarios: build_corpus(),
        }
    }

    pub fn by_team(&self, team: Team) -> Vec<&QueryScenario> {
        self.scenarios
            .iter()
            .filter(|s| s.expected_team == team)
            .collect()
    }

    pub fn by_difficulty(&self, difficulty: Difficulty) -> Vec<&QueryScenario> {
        self.scenarios
            .iter()
            .filter(|s| s.difficulty == difficulty)
            .collect()
    }

    pub fn fast_path_scenarios(&self) -> Vec<&QueryScenario> {
        self.scenarios
            .iter()
            .filter(|s| s.expected_path == ExpectedPath::FastPath)
            .collect()
    }

    pub fn learnable_scenarios(&self) -> Vec<&QueryScenario> {
        self.scenarios
            .iter()
            .filter(|s| s.expected_path == ExpectedPath::LearnableRecipe)
            .collect()
    }
}

fn build_corpus() -> Vec<QueryScenario> {
    let mut id = 0;
    let mut next_id = || {
        id += 1;
        id
    };

    vec![
        // ===== STORAGE TEAM (15 queries) =====
        QueryScenario {
            id: next_id(),
            query: "how much disk space do I have".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: Some("check free disk space".into()),
            tags: vec!["disk".into(), "fast_path".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "why is my disk full".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("disk space running out".into()),
            tags: vec!["disk".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "list all mounted filesystems".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["mount".into(), "filesystem".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "what is eating my disk space in /var".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("find large files in /var".into()),
            tags: vec!["disk".into(), "analysis".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to mount a USB drive".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("mount external drive".into()),
            tags: vec!["mount".into(), "usb".into(), "recipe".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "clean up old journal logs".into(),
            expected_team: Team::Logs, // v0.0.268: Fixed - journal logs go to Logs team
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("free disk space by removing old logs".into()),
            tags: vec!["cleanup".into(), "journal".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to resize a btrfs partition".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["btrfs".into(), "partition".into(), "risky".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "fix btrfs read-only filesystem".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["btrfs".into(), "error".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "show disk usage by directory".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("du -sh".into()),
            tags: vec!["disk".into(), "usage".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to check disk health with SMART".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("check if disk is failing".into()),
            tags: vec!["smart".into(), "health".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "create a new ext4 partition".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["partition".into(), "format".into(), "risky".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "what partitions do I have".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("show partition table".into()),
            tags: vec!["partition".into(), "list".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to check inode usage".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("disk full but files not large".into()),
            tags: vec!["inode".into(), "disk".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup automatic snapshots with btrfs".into(),
            expected_team: Team::Storage,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["btrfs".into(), "snapshot".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "find files larger than 1GB on disk".into(), // v0.0.268: Added "disk" for routing
            expected_team: Team::Storage,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("locate big files on disk".into()),
            tags: vec!["find".into(), "large".into()],
        },
        // ===== NETWORK TEAM (15 queries) =====
        QueryScenario {
            id: next_id(),
            query: "am I connected to the internet".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: Some("check network connection".into()),
            tags: vec!["network".into(), "fast_path".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "what is my IP address".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: Some("show IP".into()),
            tags: vec!["ip".into(), "fast_path".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "wifi not working after update".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["wifi".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to connect to hidden wifi network".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("connect to ssid not broadcasting".into()),
            tags: vec!["wifi".into(), "hidden".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "configure static IP address".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("set fixed IP".into()),
            tags: vec!["ip".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "DNS not resolving".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("can ping IP but not hostname".into()),
            tags: vec!["dns".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup wireguard VPN".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["vpn".into(), "wireguard".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "port 8080 already in use".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("find process using port".into()),
            tags: vec!["port".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to open port in firewall".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("allow incoming connections".into()),
            tags: vec!["firewall".into(), "port".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "network speed test from terminal".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("check bandwidth".into()),
            tags: vec!["speed".into(), "test".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "show all open network connections".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("list network sockets".into()),
            tags: vec!["netstat".into(), "connections".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "bridge two network interfaces".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["bridge".into(), "advanced".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "why is my network slow".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("diagnose slow connection".into()),
            tags: vec!["slow".into(), "diagnose".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup network bonding".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["bonding".into(), "advanced".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "restart network manager".into(),
            expected_team: Team::Network,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("reload network config".into()),
            tags: vec!["restart".into(), "service".into()],
        },
        // ===== DESKTOP TEAM (15 queries) =====
        QueryScenario {
            id: next_id(),
            query: "enable syntax highlighting in vim".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("turn on vim colors".into()),
            tags: vec!["vim".into(), "config".into(), "recipe".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "edit my vimrc".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("configure vim".into()),
            tags: vec!["vim".into(), "edit".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "set nano as default editor".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("change default text editor".into()),
            tags: vec!["nano".into(), "default".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "configure hyprland.conf".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("edit hyprland config".into()),
            tags: vec!["hyprland".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how to install gnome extensions".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["gnome".into(), "extension".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "fix screen tearing in KDE".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["kde".into(), "graphics".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "change keyboard shortcut for screenshot".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["shortcut".into(), "screenshot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "enable dark mode in gtk apps".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("dark theme for gtk".into()),
            tags: vec!["gtk".into(), "theme".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "wayland vs x11 which am I running".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("check display server".into()),
            tags: vec!["wayland".into(), "x11".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "fix blurry fonts on hidpi display".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["hidpi".into(), "fonts".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "configure neovim with lua".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["neovim".into(), "lua".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup helix editor".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["helix".into(), "editor".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "show line numbers in vim".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("vim display line numbers".into()),
            tags: vec!["vim".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "customize bash prompt".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("change PS1".into()),
            tags: vec!["bash".into(), "prompt".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "configure tmux keybindings".into(),
            expected_team: Team::Desktop,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["tmux".into(), "config".into()],
        },
        // ===== SERVICES TEAM (15 queries) =====
        QueryScenario {
            id: next_id(),
            query: "restart nginx".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("reload nginx config".into()),
            tags: vec!["nginx".into(), "restart".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "why is docker not starting".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("docker daemon won't start".into()),
            tags: vec!["docker".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "list all failed systemd services".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("show failed units".into()),
            tags: vec!["systemd".into(), "failed".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "create a systemd timer".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["systemd".into(), "timer".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "enable service to start on boot".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("autostart service".into()),
            tags: vec!["systemd".into(), "enable".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup docker compose".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["docker".into(), "compose".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "view logs for sshd".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("show ssh service logs".into()),
            tags: vec!["sshd".into(), "logs".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "configure cron job".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("schedule recurring task".into()),
            tags: vec!["cron".into(), "schedule".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "postgresql won't accept connections".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["postgresql".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "check if apache is running".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("is httpd active".into()),
            tags: vec!["apache".into(), "status".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "run docker container in background".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("docker detached mode".into()),
            tags: vec!["docker".into(), "run".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "write a custom systemd service".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["systemd".into(), "unit".into(), "create".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "limit docker container memory".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["docker".into(), "resources".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "nginx 502 bad gateway error".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["nginx".into(), "error".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "reload systemd daemon after changes".into(),
            expected_team: Team::Services,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("systemctl daemon-reload".into()),
            tags: vec!["systemd".into(), "reload".into()],
        },
        // ===== PERFORMANCE TEAM (10 queries) =====
        QueryScenario {
            id: next_id(),
            query: "why is my computer slow".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("system running slowly".into()),
            tags: vec!["slow".into(), "performance".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "what is using all my RAM".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("high memory usage".into()),
            tags: vec!["ram".into(), "memory".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "check system load".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: Some("show load average".into()),
            tags: vec!["load".into(), "fast_path".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "top cpu consuming processes".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("which process uses most cpu".into()),
            tags: vec!["cpu".into(), "process".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "enable swap on a file".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["swap".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "tune kernel for better performance".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["kernel".into(), "tune".into(), "risky".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "reduce power consumption".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("improve battery life".into()),
            tags: vec!["power".into(), "laptop".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "show cpu frequency".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["cpu".into(), "frequency".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "benchmark disk io".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["disk".into(), "benchmark".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "high iowait what does it mean".into(),
            expected_team: Team::Performance,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["io".into(), "performance".into()],
        },
        // ===== HARDWARE TEAM (10 queries) =====
        QueryScenario {
            id: next_id(),
            query: "how many CPU cores do I have".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: Some("show cpu info".into()),
            tags: vec!["cpu".into(), "info".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "which GPU is installed".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("show graphics card".into()),
            tags: vec!["gpu".into(), "detect".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "install nvidia drivers".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["nvidia".into(), "driver".into(), "risky".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "bluetooth not working".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["bluetooth".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "check RAM speed and type".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("show memory info".into()),
            tags: vec!["ram".into(), "info".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "no sound on my laptop".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("audio not working".into()),
            tags: vec!["audio".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup dual monitor".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("configure multiple displays".into()),
            tags: vec!["monitor".into(), "config".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "check CPU temperature".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("is my cpu overheating".into()),
            tags: vec!["cpu".into(), "temp".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "keyboard backlight not working".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["keyboard".into(), "hardware".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "webcam not detected".into(),
            expected_team: Team::Hardware,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["webcam".into(), "hardware".into()],
        },
        // ===== SECURITY TEAM (10 queries) =====
        QueryScenario {
            id: next_id(),
            query: "check file permissions".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("show chmod".into()),
            tags: vec!["permissions".into(), "file".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "permission denied even as root".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: None,
            tags: vec!["permissions".into(), "troubleshoot".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup ssh key authentication".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("passwordless ssh".into()),
            tags: vec!["ssh".into(), "keys".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "configure ufw firewall".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["firewall".into(), "ufw".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "harden ssh config".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["ssh".into(), "security".into(), "harden".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "check for failed login attempts".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("who tried to login".into()),
            tags: vec!["login".into(), "audit".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup fail2ban".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["fail2ban".into(), "security".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "encrypt a file with gpg".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["gpg".into(), "encrypt".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "disable root login via ssh".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["ssh".into(), "root".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "check open ports for security".into(),
            expected_team: Team::Security,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("scan local ports".into()),
            tags: vec!["ports".into(), "audit".into()],
        },
        // ===== LOGS TEAM (5 queries) =====
        QueryScenario {
            id: next_id(),
            query: "show recent errors in system log".into(),
            expected_team: Team::Logs,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("check syslog errors".into()),
            tags: vec!["logs".into(), "errors".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "view kernel messages from last boot".into(),
            expected_team: Team::Logs,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::JuniorOnly,
            similar_query: Some("dmesg from previous boot".into()),
            tags: vec!["dmesg".into(), "kernel".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "follow live journalctl output".into(),
            expected_team: Team::Logs,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("tail system logs".into()),
            tags: vec!["journal".into(), "live".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "analyze why system crashed".into(),
            expected_team: Team::Logs,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["crash".into(), "analyze".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "setup centralized logging".into(),
            expected_team: Team::Logs,
            difficulty: Difficulty::Complex,
            expected_path: ExpectedPath::SeniorReview,
            similar_query: None,
            tags: vec!["logging".into(), "config".into()],
        },
        // ===== GENERAL (5 queries) =====
        QueryScenario {
            id: next_id(),
            query: "how is my computer".into(),
            expected_team: Team::General,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: Some("system status".into()),
            tags: vec!["health".into(), "fast_path".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "what changed since yesterday".into(),
            expected_team: Team::General,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::FastPath,
            similar_query: None,
            tags: vec!["changes".into(), "fast_path".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "how do I update my system".into(),
            expected_team: Team::General,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("run system update".into()),
            tags: vec!["update".into(), "package".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "install htop".into(),
            expected_team: Team::General,
            difficulty: Difficulty::Simple,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: Some("get htop package".into()),
            tags: vec!["install".into(), "package".into()],
        },
        QueryScenario {
            id: next_id(),
            query: "backup my home directory".into(),
            expected_team: Team::General,
            difficulty: Difficulty::Medium,
            expected_path: ExpectedPath::LearnableRecipe,
            similar_query: None,
            tags: vec!["backup".into(), "files".into()],
        },
    ]
}
