//! Default probe primitive definitions.

use super::domain::{Domain, ParserId};
use super::precondition::Precondition;
use super::probe_primitive::ProbePrimitive;

/// Get the default set of probe primitives.
pub fn default_primitives() -> Vec<ProbePrimitive> {
    vec![
        // === Boot ===
        ProbePrimitive {
            id: "sys.boot.analyze",
            domain: Domain::Boot,
            purpose: "Get boot time breakdown",
            command_template: "systemd-analyze",
            timeout_ms: 5000,
            parser: ParserId::TimeDuration,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("systemd-analyze"),
            keywords: &["boot", "startup", "time", "slow"],
        },
        ProbePrimitive {
            id: "sys.boot.blame",
            domain: Domain::Boot,
            purpose: "List units by startup time",
            command_template: "systemd-analyze blame --no-pager | head -50",
            timeout_ms: 5000,
            parser: ParserId::Table,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("systemd-analyze"),
            keywords: &["boot", "slow", "units", "blame", "startup"],
        },
        ProbePrimitive {
            id: "sys.boot.critical",
            domain: Domain::Boot,
            purpose: "Show critical chain for boot",
            command_template: "systemd-analyze critical-chain --no-pager",
            timeout_ms: 5000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("systemd-analyze"),
            keywords: &["boot", "critical", "chain", "dependency"],
        },
        // === Services ===
        ProbePrimitive {
            id: "sys.services.failed",
            domain: Domain::Services,
            purpose: "List failed systemd units",
            command_template: "systemctl --failed --no-pager --plain",
            timeout_ms: 3000,
            parser: ParserId::Table,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("systemctl"),
            keywords: &["failed", "services", "units", "error"],
        },
        ProbePrimitive {
            id: "sys.services.list",
            domain: Domain::Services,
            purpose: "List running services",
            command_template: "systemctl list-units --type=service --state=running --no-pager --plain",
            timeout_ms: 3000,
            parser: ParserId::Table,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("systemctl"),
            keywords: &["services", "running", "active", "list"],
        },
        ProbePrimitive {
            id: "sys.services.timers",
            domain: Domain::Services,
            purpose: "List active timers",
            command_template: "systemctl list-timers --no-pager --plain",
            timeout_ms: 3000,
            parser: ParserId::Table,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("systemctl"),
            keywords: &["timers", "scheduled", "cron"],
        },
        // === Logs ===
        ProbePrimitive {
            id: "sys.logs.errors",
            domain: Domain::Logs,
            purpose: "Recent error-level log entries",
            command_template: "journalctl -p err..alert -n 20 --no-pager",
            timeout_ms: 5000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("journalctl"),
            keywords: &["errors", "logs", "journal", "alert"],
        },
        ProbePrimitive {
            id: "sys.logs.boot",
            domain: Domain::Logs,
            purpose: "Current boot log entries",
            command_template: "journalctl -b -n 50 --no-pager",
            timeout_ms: 5000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::SystemdRunning],
            related_man: Some("journalctl"),
            keywords: &["boot", "logs", "journal", "startup"],
        },
        // === Memory ===
        ProbePrimitive {
            id: "sys.mem.free",
            domain: Domain::Memory,
            purpose: "Memory usage from /proc/meminfo",
            command_template: "cat /proc/meminfo",
            timeout_ms: 1000,
            parser: ParserId::KeyValue,
            preconditions: &[Precondition::FileExists("/proc/meminfo")],
            related_man: Some("proc"),
            keywords: &["memory", "ram", "free", "available"],
        },
        ProbePrimitive {
            id: "sys.mem.usage",
            domain: Domain::Memory,
            purpose: "Memory usage summary",
            command_template: "free -h",
            timeout_ms: 1000,
            parser: ParserId::Table,
            preconditions: &[Precondition::CommandExists("free")],
            related_man: Some("free"),
            keywords: &["memory", "ram", "usage", "swap"],
        },
        // === Disk ===
        ProbePrimitive {
            id: "sys.disk.df",
            domain: Domain::Disk,
            purpose: "Filesystem disk usage",
            command_template: "df -h",
            timeout_ms: 2000,
            parser: ParserId::Table,
            preconditions: &[Precondition::CommandExists("df")],
            related_man: Some("df"),
            keywords: &["disk", "space", "filesystem", "usage"],
        },
        ProbePrimitive {
            id: "sys.disk.inodes",
            domain: Domain::Disk,
            purpose: "Inode usage",
            command_template: "df -i",
            timeout_ms: 2000,
            parser: ParserId::Table,
            preconditions: &[Precondition::CommandExists("df")],
            related_man: Some("df"),
            keywords: &["inodes", "disk", "filesystem"],
        },
        ProbePrimitive {
            id: "sys.disk.mounts",
            domain: Domain::Disk,
            purpose: "Current mounts",
            command_template: "mount | grep -E '^/dev'",
            timeout_ms: 2000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("mount")],
            related_man: Some("mount"),
            keywords: &["mounts", "disk", "filesystem", "partition"],
        },
        // === Network ===
        ProbePrimitive {
            id: "net.ip.addr",
            domain: Domain::Network,
            purpose: "IP addresses and interfaces",
            command_template: "ip addr",
            timeout_ms: 2000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("ip")],
            related_man: Some("ip-address"),
            keywords: &["ip", "address", "interface", "network"],
        },
        ProbePrimitive {
            id: "net.ip.route",
            domain: Domain::Network,
            purpose: "Routing table",
            command_template: "ip route",
            timeout_ms: 2000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("ip")],
            related_man: Some("ip-route"),
            keywords: &["route", "gateway", "network"],
        },
        ProbePrimitive {
            id: "net.dns.resolv",
            domain: Domain::Network,
            purpose: "DNS configuration",
            command_template: "cat /etc/resolv.conf",
            timeout_ms: 1000,
            parser: ParserId::KeyValue,
            preconditions: &[Precondition::FileExists("/etc/resolv.conf")],
            related_man: Some("resolv.conf"),
            keywords: &["dns", "nameserver", "resolver"],
        },
        ProbePrimitive {
            id: "net.connections",
            domain: Domain::Network,
            purpose: "Active network connections",
            command_template: "ss -tuln",
            timeout_ms: 3000,
            parser: ParserId::Table,
            preconditions: &[Precondition::CommandExists("ss")],
            related_man: Some("ss"),
            keywords: &["connections", "ports", "listening", "tcp", "udp"],
        },
        // === Hardware ===
        ProbePrimitive {
            id: "hw.cpu.info",
            domain: Domain::Hardware,
            purpose: "CPU information",
            command_template: "cat /proc/cpuinfo | head -50",
            timeout_ms: 1000,
            parser: ParserId::KeyValue,
            preconditions: &[Precondition::FileExists("/proc/cpuinfo")],
            related_man: Some("proc"),
            keywords: &["cpu", "processor", "cores"],
        },
        ProbePrimitive {
            id: "hw.cpu.temp",
            domain: Domain::Hardware,
            purpose: "CPU temperature",
            command_template: "sensors 2>/dev/null || cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null",
            timeout_ms: 3000,
            parser: ParserId::Raw,
            preconditions: &[],
            related_man: Some("sensors"),
            keywords: &["temperature", "temp", "cpu", "thermal", "hot"],
        },
        ProbePrimitive {
            id: "hw.pci",
            domain: Domain::Hardware,
            purpose: "PCI devices",
            command_template: "lspci -v | head -100",
            timeout_ms: 3000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("lspci")],
            related_man: Some("lspci"),
            keywords: &["pci", "hardware", "devices", "gpu", "network"],
        },
        ProbePrimitive {
            id: "hw.usb",
            domain: Domain::Hardware,
            purpose: "USB devices",
            command_template: "lsusb",
            timeout_ms: 2000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("lsusb")],
            related_man: Some("lsusb"),
            keywords: &["usb", "devices", "peripheral"],
        },
        // === Performance ===
        ProbePrimitive {
            id: "perf.load",
            domain: Domain::Performance,
            purpose: "System load averages",
            command_template: "cat /proc/loadavg",
            timeout_ms: 1000,
            parser: ParserId::Numeric,
            preconditions: &[Precondition::FileExists("/proc/loadavg")],
            related_man: Some("proc"),
            keywords: &["load", "average", "performance"],
        },
        ProbePrimitive {
            id: "perf.uptime",
            domain: Domain::Performance,
            purpose: "System uptime",
            command_template: "uptime",
            timeout_ms: 1000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("uptime")],
            related_man: Some("uptime"),
            keywords: &["uptime", "running", "time"],
        },
        ProbePrimitive {
            id: "perf.top",
            domain: Domain::Performance,
            purpose: "Top processes by CPU",
            command_template: "ps aux --sort=-%cpu | head -15",
            timeout_ms: 3000,
            parser: ParserId::Table,
            preconditions: &[Precondition::CommandExists("ps")],
            related_man: Some("ps"),
            keywords: &["processes", "cpu", "top", "usage"],
        },
        // === Packages ===
        ProbePrimitive {
            id: "pkg.pacman.recent",
            domain: Domain::Packages,
            purpose: "Recently installed packages",
            command_template: "grep -E 'installed|upgraded' /var/log/pacman.log | tail -20",
            timeout_ms: 2000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::FileExists("/var/log/pacman.log")],
            related_man: Some("pacman"),
            keywords: &["packages", "installed", "recent", "pacman"],
        },
        ProbePrimitive {
            id: "pkg.pacman.orphans",
            domain: Domain::Packages,
            purpose: "Orphaned packages",
            command_template: "pacman -Qdt",
            timeout_ms: 5000,
            parser: ParserId::Raw,
            preconditions: &[Precondition::CommandExists("pacman")],
            related_man: Some("pacman"),
            keywords: &["orphans", "packages", "unused"],
        },
    ]
}
