//! Neovim Installation Recipe
//!
//! Beta.151: Deterministic recipe for installing Neovim with basic configuration
//!
//! This module generates a safe ActionPlan for:
//! - Installing Neovim from Arch repos
//! - Creating basic init.vim/init.lua configuration
//! - Setting up plugin directory structure
//! - Verifying installation

use anna_common::action_plan_v3::{
    ActionPlan, CommandStep, DetectionResults, NecessaryCheck, PlanMeta, RiskLevel, RollbackStep,
};
use anyhow::Result;
use std::collections::HashMap;

/// Neovim installation scenario detector
pub struct NeovimRecipe;

impl NeovimRecipe {
    /// Check if user request matches neovim installation
    pub fn matches_request(user_input: &str) -> bool {
        let input_lower = user_input.to_lowercase();

        (input_lower.contains("neovim") || input_lower.contains("nvim"))
            && (input_lower.contains("install")
                || input_lower.contains("setup")
                || input_lower.contains("config")
                || input_lower.contains("get"))
    }

    /// Generate neovim installation ActionPlan
    pub fn build_plan(telemetry: &HashMap<String, String>) -> Result<ActionPlan> {
        let has_internet = telemetry
            .get("internet_connected")
            .map(|v| v == "true")
            .unwrap_or(false);

        let user_home = telemetry.get("home").map(|s| s.as_str()).unwrap_or("~");

        let necessary_checks = vec![
            NecessaryCheck {
                id: "check-internet".to_string(),
                description: "Verify internet connectivity for package download".to_string(),
                command: "ping -c 1 archlinux.org".to_string(),
                risk_level: RiskLevel::Info,
                required: true,
            },
            NecessaryCheck {
                id: "check-neovim-installed".to_string(),
                description: "Check if Neovim is already installed".to_string(),
                command: "pacman -Q neovim".to_string(),
                risk_level: RiskLevel::Info,
                required: false,
            },
            NecessaryCheck {
                id: "check-config-exists".to_string(),
                description: "Check if Neovim config directory exists".to_string(),
                command: format!("ls -la {}/.config/nvim/", user_home),
                risk_level: RiskLevel::Info,
                required: false,
            },
        ];

        let command_plan = vec![
            CommandStep {
                id: "install-neovim".to_string(),
                description: "Install Neovim text editor from Arch repositories".to_string(),
                command: "sudo pacman -S --noconfirm neovim".to_string(),
                risk_level: RiskLevel::Medium,
                rollback_id: Some("remove-neovim".to_string()),
                requires_confirmation: true,
            },
            CommandStep {
                id: "create-config-dir".to_string(),
                description: "Create Neovim configuration directory".to_string(),
                command: format!("mkdir -p {}/.config/nvim", user_home),
                risk_level: RiskLevel::Low,
                rollback_id: None,
                requires_confirmation: false,
            },
            CommandStep {
                id: "create-basic-init".to_string(),
                description: "Create basic init.lua with sensible defaults".to_string(),
                command: format!(
                    "cat > {}/.config/nvim/init.lua << 'EOF'\n\
                    -- Basic Neovim Configuration\n\
                    -- Generated by Anna Assistant\n\
                    \n\
                    -- Enable line numbers\n\
                    vim.opt.number = true\n\
                    vim.opt.relativenumber = true\n\
                    \n\
                    -- Set tabs to 4 spaces\n\
                    vim.opt.tabstop = 4\n\
                    vim.opt.shiftwidth = 4\n\
                    vim.opt.expandtab = true\n\
                    \n\
                    -- Enable mouse support\n\
                    vim.opt.mouse = 'a'\n\
                    \n\
                    -- Enable syntax highlighting\n\
                    vim.cmd('syntax enable')\n\
                    \n\
                    -- Set color scheme (if available)\n\
                    vim.cmd('silent! colorscheme habamax')\n\
                    \n\
                    -- Enable smart search\n\
                    vim.opt.ignorecase = true\n\
                    vim.opt.smartcase = true\n\
                    \n\
                    -- Show matching brackets\n\
                    vim.opt.showmatch = true\n\
                    \n\
                    -- Enable clipboard integration\n\
                    vim.opt.clipboard = 'unnamedplus'\n\
                    \n\
                    print('Neovim configured by Anna Assistant')\n\
                    EOF",
                    user_home
                ),
                risk_level: RiskLevel::Low,
                rollback_id: Some("remove-init-config".to_string()),
                requires_confirmation: false,
            },
            CommandStep {
                id: "verify-neovim".to_string(),
                description: "Verify Neovim installation and configuration".to_string(),
                command: "nvim --version && ls -la ~/.config/nvim/init.lua".to_string(),
                risk_level: RiskLevel::Info,
                rollback_id: None,
                requires_confirmation: false,
            },
        ];

        let rollback_plan = vec![
            RollbackStep {
                id: "remove-init-config".to_string(),
                description: "Remove generated init.lua configuration".to_string(),
                command: format!("rm -f {}/.config/nvim/init.lua", user_home),
            },
            RollbackStep {
                id: "remove-neovim".to_string(),
                description: "Uninstall Neovim package".to_string(),
                command: "sudo pacman -Rns --noconfirm neovim".to_string(),
            },
        ];

        let mut analysis_parts =
            vec!["User requests Neovim installation with basic configuration.".to_string()];

        if !has_internet {
            analysis_parts.push(
                "⚠️ WARNING: Internet connectivity not confirmed. Installation requires network access."
                    .to_string(),
            );
        }

        let analysis = analysis_parts.join(" ");

        let goals = vec![
            "Install Neovim text editor from Arch repositories".to_string(),
            "Create configuration directory structure".to_string(),
            "Generate basic init.lua with sensible defaults".to_string(),
            "Verify successful installation".to_string(),
        ];

        let notes_for_user = format!(
            "This will install Neovim and create a basic configuration with:\n\
             • Line numbers and relative line numbers\n\
             • 4-space tabs with smart indentation\n\
             • Mouse support enabled\n\
             • Syntax highlighting\n\
             • Smart case-insensitive search\n\
             • Clipboard integration\n\n\
             Configuration location: {}/.config/nvim/init.lua\n\n\
             After installation, run 'nvim' to start Neovim.\n\
             To customize further, edit ~/.config/nvim/init.lua\n\n\
             Plugin management:\n\
             Consider installing a plugin manager like 'packer.nvim' or 'lazy.nvim' later.\n\n\
             Estimated disk usage: ~50-100 MB\n\
             Estimated time: 30-60 seconds",
            user_home
        );

        // Metadata (Beta.151: Use PlanMeta for recipe tracking)
        let mut other = HashMap::new();
        other.insert(
            "recipe_module".to_string(),
            serde_json::Value::String("neovim.rs".to_string()),
        );
        other.insert(
            "has_internet".to_string(),
            serde_json::Value::String(has_internet.to_string()),
        );
        other.insert(
            "config_type".to_string(),
            serde_json::Value::String("init.lua".to_string()),
        );

        let meta = PlanMeta {
            detection_results: DetectionResults {
                de: None,
                wm: None,
                wallpaper_backends: vec![],
                display_protocol: None,
                other,
            },
            template_used: Some("neovim_install".to_string()),
            llm_version: "deterministic_recipe_v1".to_string(),
        };

        Ok(ActionPlan {
            analysis,
            goals,
            necessary_checks,
            command_plan,
            rollback_plan,
            notes_for_user,
            meta,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_matches_neovim_install() {
        assert!(NeovimRecipe::matches_request("install neovim"));
        assert!(NeovimRecipe::matches_request("setup nvim"));
        assert!(NeovimRecipe::matches_request("install neovim with config"));
        assert!(NeovimRecipe::matches_request("get neovim"));

        // Should not match
        assert!(!NeovimRecipe::matches_request("what is neovim"));
        assert!(!NeovimRecipe::matches_request("how to use nvim"));
    }

    #[test]
    fn test_build_neovim_plan() {
        let mut telemetry = HashMap::new();
        telemetry.insert("internet_connected".to_string(), "true".to_string());
        telemetry.insert("home".to_string(), "/home/testuser".to_string());

        let plan = NeovimRecipe::build_plan(&telemetry).unwrap();

        // Verify structure
        assert_eq!(plan.goals.len(), 4);
        assert_eq!(plan.necessary_checks.len(), 3);
        assert_eq!(plan.command_plan.len(), 4); // install, create dir, create config, verify
        assert_eq!(plan.rollback_plan.len(), 2);

        // Verify commands
        assert!(plan.command_plan[0].command.contains("pacman -S"));
        assert!(plan.command_plan[0].command.contains("neovim"));
        assert!(plan.command_plan[1].command.contains("mkdir"));
        assert!(plan.command_plan[1].command.contains(".config/nvim"));
        assert!(plan.command_plan[2].command.contains("init.lua"));

        // Verify metadata
        assert_eq!(plan.meta.template_used.as_ref().unwrap(), "neovim_install");
        assert_eq!(plan.meta.llm_version, "deterministic_recipe_v1");
    }

    #[test]
    fn test_config_contains_sensible_defaults() {
        let mut telemetry = HashMap::new();
        telemetry.insert("internet_connected".to_string(), "true".to_string());
        telemetry.insert("home".to_string(), "/home/testuser".to_string());

        let plan = NeovimRecipe::build_plan(&telemetry).unwrap();

        // Verify init.lua command contains key config options
        let init_command = &plan.command_plan[2].command;
        assert!(init_command.contains("vim.opt.number"));
        assert!(init_command.contains("vim.opt.tabstop"));
        assert!(init_command.contains("vim.opt.mouse"));
        assert!(init_command.contains("vim.opt.clipboard"));
    }

    #[test]
    fn test_no_internet_warning() {
        let mut telemetry = HashMap::new();
        telemetry.insert("internet_connected".to_string(), "false".to_string());
        telemetry.insert("home".to_string(), "/home/testuser".to_string());

        let plan = NeovimRecipe::build_plan(&telemetry).unwrap();

        // Should contain warning about internet
        assert!(plan.analysis.contains("WARNING"));
        assert!(plan.analysis.contains("Internet connectivity"));
    }
}
