//! Query class enum definition (v0.0.172).
//!
//! Defines all known query classes for deterministic routing.

use serde::{Deserialize, Serialize};

/// Known query classes with deterministic routing
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum QueryClass {
    SystemTriage,
    CpuInfo,
    CpuCores,
    CpuTemp,
    RamInfo,
    GpuInfo,
    HardwareAudio,
    TopMemoryProcesses,
    TopCpuProcesses,
    DiskSpace,
    NetworkInterfaces,
    Help,
    SystemSlow,
    MemoryUsage,
    MemoryFree,
    DiskUsage,
    LargestFolders, // v0.0.390: "top folders", "what's taking space"
    ServiceStatus,
    SystemHealthSummary,
    BootTimeStatus,
    BootBlame, // v0.0.799: "why is my boot slow?", "slow boot analysis"
    InstalledPackagesOverview,
    PackageCount,
    InstalledToolCheck,
    AppAlternatives,
    ConfigureEditor,
    MetaSmallTalk,
    KernelVersion,
    ConfigFileLocation,
    InstallPackage,
    ManageService,
    ConfigureShell,
    ConfigureGit,
    SshKeyManagement,
    TicketHistory,
    StaffRoster,
    PackageUpdates,
    SwapInfo,
    TimezoneInfo,
    SystemUptime,
    LoggedInUsers,
    BatteryStatus,
    SystemLoad,
    LastBoot,
    Hostname,
    OsInfo,
    NetworkConnectivity,
    MountedFilesystems,
    UsbDevices,
    ListeningPorts,
    RunningServices,
    CurrentUser,
    SystemArchitecture,
    EnvironmentVars,
    ProcessTree,
    DnsServers,
    DefaultGateway,
    OpenFiles,
    SystemLocale,
    BlockDevices,
    InstalledKernels,
    CpuFrequency,
    MemorySlots,
    ZfsStatus,
    BootLoader,
    FirewallStatus,
    SystemdUnits,
    Crontabs,
    SshConnections,
    DockerContainers,
    DockerImages,
    SystemdTimers,
    LastLogins,
    FailedLogins,
    SystemdJournal,
    NetworkNamespaces,
    AvailableShells,
    SudoersInfo,
    InstalledDesktops,
    VirtualizationInfo,
    SelinuxStatus,
    AppArmorStatus,
    SystemdSlices,
    CoredumpList,
    KernelModules,
    SystemdTargets,
    IpRoutes,
    ArpTable,
    IptablesRules,
    PciDevices,
    DmesgErrors,
    SystemdSockets,
    TmpFiles,
    UserGroups,
    LvmStatus,
    RaidStatus,
    NtpStatus,
    SensorsTemp,
    GpuMemory,
    XorgLog,
    BluetoothDevices,
    WirelessNetworks,
    PrinterStatus,
    AudioDevices,
    SystemdPaths,
    SystemctlMask,
    HostsFile,
    FstabEntries,
    SysctlSettings,
    LoginctlSessions,
    EnvironmentVariables,
    SystemdScopes,
    KernelCmdline,
    ModuleParams,
    NetworkBonding,
    SwapFiles,
    CpuGovernor,
    SystemdMounts,
    LoadedFirmware,
    NetworkStats,
    /// v0.0.309: Desktop wallpaper info
    DesktopWallpaper,
    /// v0.0.311: System update request
    SystemUpdate,
    /// v0.0.801: Device type (laptop/desktop)
    DeviceType,
    /// v0.0.802: Webcam/camera detection
    WebcamStatus,
    /// v0.0.805: Screen/display/monitor resolution
    ScreenResolution,
    Unknown,
}

impl std::fmt::Display for QueryClass {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::SystemTriage => "system_triage",
            Self::CpuInfo => "cpu_info",
            Self::CpuCores => "cpu_cores",
            Self::CpuTemp => "cpu_temp",
            Self::RamInfo => "ram_info",
            Self::GpuInfo => "gpu_info",
            Self::HardwareAudio => "hardware_audio",
            Self::TopMemoryProcesses => "top_memory_processes",
            Self::TopCpuProcesses => "top_cpu_processes",
            Self::DiskSpace => "disk_space",
            Self::NetworkInterfaces => "network_interfaces",
            Self::Help => "help",
            Self::SystemSlow => "system_slow",
            Self::MemoryUsage => "memory_usage",
            Self::MemoryFree => "memory_free",
            Self::DiskUsage => "disk_usage",
            Self::LargestFolders => "largest_folders",
            Self::ServiceStatus => "service_status",
            Self::SystemHealthSummary => "system_health_summary",
            Self::BootTimeStatus => "boot_time_status",
            Self::BootBlame => "boot_blame",
            Self::InstalledPackagesOverview => "installed_packages_overview",
            Self::PackageCount => "package_count",
            Self::InstalledToolCheck => "installed_tool_check",
            Self::AppAlternatives => "app_alternatives",
            Self::ConfigureEditor => "configure_editor",
            Self::MetaSmallTalk => "meta_small_talk",
            Self::KernelVersion => "kernel_version",
            Self::ConfigFileLocation => "config_file_location",
            Self::InstallPackage => "install_package",
            Self::ManageService => "manage_service",
            Self::ConfigureShell => "configure_shell",
            Self::ConfigureGit => "configure_git",
            Self::SshKeyManagement => "ssh_key_management",
            Self::TicketHistory => "ticket_history",
            Self::StaffRoster => "staff_roster",
            Self::PackageUpdates => "package_updates",
            Self::SwapInfo => "swap_info",
            Self::TimezoneInfo => "timezone_info",
            Self::SystemUptime => "system_uptime",
            Self::LoggedInUsers => "logged_in_users",
            Self::BatteryStatus => "battery_status",
            Self::SystemLoad => "system_load",
            Self::LastBoot => "last_boot",
            Self::Hostname => "hostname",
            Self::OsInfo => "os_info",
            Self::NetworkConnectivity => "network_connectivity",
            Self::MountedFilesystems => "mounted_filesystems",
            Self::UsbDevices => "usb_devices",
            Self::ListeningPorts => "listening_ports",
            Self::RunningServices => "running_services",
            Self::CurrentUser => "current_user",
            Self::SystemArchitecture => "system_architecture",
            Self::EnvironmentVars => "environment_vars",
            Self::ProcessTree => "process_tree",
            Self::DnsServers => "dns_servers",
            Self::DefaultGateway => "default_gateway",
            Self::OpenFiles => "open_files",
            Self::SystemLocale => "system_locale",
            Self::BlockDevices => "block_devices",
            Self::InstalledKernels => "installed_kernels",
            Self::CpuFrequency => "cpu_frequency",
            Self::MemorySlots => "memory_slots",
            Self::ZfsStatus => "zfs_status",
            Self::BootLoader => "boot_loader",
            Self::FirewallStatus => "firewall_status",
            Self::SystemdUnits => "systemd_units",
            Self::Crontabs => "crontabs",
            Self::SshConnections => "ssh_connections",
            Self::DockerContainers => "docker_containers",
            Self::DockerImages => "docker_images",
            Self::SystemdTimers => "systemd_timers",
            Self::LastLogins => "last_logins",
            Self::FailedLogins => "failed_logins",
            Self::SystemdJournal => "systemd_journal",
            Self::NetworkNamespaces => "network_namespaces",
            Self::AvailableShells => "available_shells",
            Self::SudoersInfo => "sudoers_info",
            Self::InstalledDesktops => "installed_desktops",
            Self::VirtualizationInfo => "virtualization_info",
            Self::SelinuxStatus => "selinux_status",
            Self::AppArmorStatus => "apparmor_status",
            Self::SystemdSlices => "systemd_slices",
            Self::CoredumpList => "coredump_list",
            Self::KernelModules => "kernel_modules",
            Self::SystemdTargets => "systemd_targets",
            Self::IpRoutes => "ip_routes",
            Self::ArpTable => "arp_table",
            Self::IptablesRules => "iptables_rules",
            Self::PciDevices => "pci_devices",
            Self::DmesgErrors => "dmesg_errors",
            Self::SystemdSockets => "systemd_sockets",
            Self::TmpFiles => "tmp_files",
            Self::UserGroups => "user_groups",
            Self::LvmStatus => "lvm_status",
            Self::RaidStatus => "raid_status",
            Self::NtpStatus => "ntp_status",
            Self::SensorsTemp => "sensors_temp",
            Self::GpuMemory => "gpu_memory",
            Self::XorgLog => "xorg_log",
            Self::BluetoothDevices => "bluetooth_devices",
            Self::WirelessNetworks => "wireless_networks",
            Self::PrinterStatus => "printer_status",
            Self::AudioDevices => "audio_devices",
            Self::SystemdPaths => "systemd_paths",
            Self::SystemctlMask => "systemctl_mask",
            Self::HostsFile => "hosts_file",
            Self::FstabEntries => "fstab_entries",
            Self::SysctlSettings => "sysctl_settings",
            Self::LoginctlSessions => "loginctl_sessions",
            Self::EnvironmentVariables => "environment_variables",
            Self::SystemdScopes => "systemd_scopes",
            Self::KernelCmdline => "kernel_cmdline",
            Self::ModuleParams => "module_params",
            Self::NetworkBonding => "network_bonding",
            Self::SwapFiles => "swap_files",
            Self::CpuGovernor => "cpu_governor",
            Self::SystemdMounts => "systemd_mounts",
            Self::LoadedFirmware => "loaded_firmware",
            Self::NetworkStats => "network_stats",
            Self::DesktopWallpaper => "desktop_wallpaper",
            Self::SystemUpdate => "system_update",
            Self::DeviceType => "device_type",
            Self::WebcamStatus => "webcam_status",
            Self::ScreenResolution => "screen_resolution",
            Self::Unknown => "unknown",
        };
        write!(f, "{}", s)
    }
}
