//! Settings documentation modules (v0.0.693-720)

#[path = "../settings_ledger/mod.rs"]
pub mod settings_ledger;
#[path = "../settings_diary/mod.rs"]
pub mod settings_diary;
#[path = "../settings_folio/mod.rs"]
pub mod settings_folio;
#[path = "../settings_album/mod.rs"]
pub mod settings_album;
#[path = "../settings_dossier/mod.rs"]
pub mod settings_dossier;
#[path = "../settings_portfolio/mod.rs"]
pub mod settings_portfolio;
#[path = "../settings_catalog_v2/mod.rs"]
pub mod settings_catalog_v2;
#[path = "../settings_compendium/mod.rs"]
pub mod settings_compendium; // v0.0.700: Milestone!
#[path = "../settings_anthology/mod.rs"]
pub mod settings_anthology;
#[path = "../settings_archive_v2/mod.rs"]
pub mod settings_archive_v2;
#[path = "../settings_repertoire/mod.rs"]
pub mod settings_repertoire;
#[path = "../settings_gazette/mod.rs"]
pub mod settings_gazette;
#[path = "../settings_almanac/mod.rs"]
pub mod settings_almanac;
#[path = "../settings_bulletin/mod.rs"]
pub mod settings_bulletin;
#[path = "../settings_journal/mod.rs"]
pub mod settings_journal;
// Module now in settings_memo/
#[path = "../settings_memo/mod.rs"]
pub mod settings_memo;
#[path = "../settings_digest/mod.rs"]
pub mod settings_digest;
#[path = "../settings_brief/mod.rs"]
pub mod settings_brief;
#[path = "../settings_summary/mod.rs"]
pub mod settings_summary;
#[path = "../settings_report/mod.rs"]
pub mod settings_report;
#[path = "../settings_notice/mod.rs"]
pub mod settings_notice;
#[path = "../settings_dispatch/mod.rs"]
pub mod settings_dispatch;
#[path = "../settings_communique/mod.rs"]
pub mod settings_communique;
#[path = "../settings_missive/mod.rs"]
pub mod settings_missive;
#[path = "../settings_circular/mod.rs"]
pub mod settings_circular;
#[path = "../settings_directive/mod.rs"]
pub mod settings_directive;
#[path = "../settings_edict/mod.rs"]
pub mod settings_edict;
