//! Settings geography modules (v0.0.750-786)

#[path = "../settings_municipality/mod.rs"]
pub mod settings_municipality;
#[path = "../settings_borough/mod.rs"]
pub mod settings_borough;
#[path = "../settings_ward/mod.rs"]
pub mod settings_ward;
#[path = "../settings_precinct/mod.rs"]
pub mod settings_precinct;
#[path = "../settings_neighborhood/mod.rs"]
pub mod settings_neighborhood;
#[path = "../settings_block/mod.rs"]
pub mod settings_block;
#[path = "../settings_lot/mod.rs"]
pub mod settings_lot;
#[path = "../settings_parcel/mod.rs"]
pub mod settings_parcel;
#[path = "../settings_plot/mod.rs"]
pub mod settings_plot;
#[path = "../settings_tract/mod.rs"]
pub mod settings_tract;
#[path = "../settings_acre/mod.rs"]
pub mod settings_acre;
#[path = "../settings_hectare/mod.rs"]
pub mod settings_hectare;
#[path = "../settings_field/mod.rs"]
pub mod settings_field;
#[path = "../settings_meadow/mod.rs"]
pub mod settings_meadow;
#[path = "../settings_pasture/mod.rs"]
pub mod settings_pasture;
#[path = "../settings_grove/mod.rs"]
pub mod settings_grove;
#[path = "../settings_orchard/mod.rs"]
pub mod settings_orchard;
#[path = "../settings_vineyard/mod.rs"]
pub mod settings_vineyard;
#[path = "../settings_garden/mod.rs"]
pub mod settings_garden;
#[path = "../settings_nursery/mod.rs"]
pub mod settings_nursery;
#[path = "../settings_greenhouse/mod.rs"]
pub mod settings_greenhouse;
#[path = "../settings_conservatory/mod.rs"]
pub mod settings_conservatory;
#[path = "../settings_arboretum/mod.rs"]
pub mod settings_arboretum;
#[path = "../settings_botanical/mod.rs"]
pub mod settings_botanical;
#[path = "../settings_herbarium/mod.rs"]
pub mod settings_herbarium;
#[path = "../settings_aquarium/mod.rs"]
pub mod settings_aquarium;
#[path = "../settings_vivarium/mod.rs"]
pub mod settings_vivarium;
#[path = "../settings_terrarium/mod.rs"]
pub mod settings_terrarium;
#[path = "../settings_aviary/mod.rs"]
pub mod settings_aviary;
#[path = "../settings_apiary/mod.rs"]
pub mod settings_apiary;
#[path = "../settings_butterfly/mod.rs"]
pub mod settings_butterfly;
#[path = "../settings_sanctuary/mod.rs"]
pub mod settings_sanctuary;
#[path = "../settings_reserve/mod.rs"]
pub mod settings_reserve;
#[path = "../settings_refuge/mod.rs"]
pub mod settings_refuge;
#[path = "../settings_haven/mod.rs"]
pub mod settings_haven;
#[path = "../settings_retreat/mod.rs"]
pub mod settings_retreat;
#[path = "../settings_hideaway/mod.rs"]
pub mod settings_hideaway;
