//! Settings governance modules (v0.0.720-750)

#[path = "../settings_decree/mod.rs"]
pub mod settings_decree;
#[path = "../settings_mandate/mod.rs"]
pub mod settings_mandate;
#[path = "../settings_ordinance/mod.rs"]
pub mod settings_ordinance;
#[path = "../settings_statute/mod.rs"]
pub mod settings_statute;
#[path = "../settings_charter/mod.rs"]
pub mod settings_charter;
#[path = "../settings_constitution/mod.rs"]
pub mod settings_constitution;
#[path = "../settings_covenant/mod.rs"]
pub mod settings_covenant;
#[path = "../settings_treaty/mod.rs"]
pub mod settings_treaty;
#[path = "../settings_protocol/mod.rs"]
pub mod settings_protocol;
#[path = "../settings_compact/mod.rs"]
pub mod settings_compact;
#[path = "../settings_accord/mod.rs"]
pub mod settings_accord;
#[path = "../settings_pact/mod.rs"]
pub mod settings_pact;
#[path = "../settings_concordat/mod.rs"]
pub mod settings_concordat;
#[path = "../settings_convention/mod.rs"]
pub mod settings_convention;
#[path = "../settings_entente/mod.rs"]
pub mod settings_entente;
#[path = "../settings_alliance/mod.rs"]
pub mod settings_alliance;
#[path = "../settings_coalition/mod.rs"]
pub mod settings_coalition;
#[path = "../settings_federation/mod.rs"]
pub mod settings_federation;
#[path = "../settings_confederation/mod.rs"]
pub mod settings_confederation;
#[path = "../settings_union/mod.rs"]
pub mod settings_union;
#[path = "../settings_bloc/mod.rs"]
pub mod settings_bloc;
#[path = "../settings_sphere/mod.rs"]
pub mod settings_sphere;
#[path = "../settings_zone/mod.rs"]
pub mod settings_zone;
#[path = "../settings_domain/mod.rs"]
pub mod settings_domain;
#[path = "../settings_realm/mod.rs"]
pub mod settings_realm;
#[path = "../settings_territory/mod.rs"]
pub mod settings_territory;
#[path = "../settings_province/mod.rs"]
pub mod settings_province;
#[path = "../settings_region/mod.rs"]
pub mod settings_region;
#[path = "../settings_district/mod.rs"]
pub mod settings_district;
#[path = "../settings_county/mod.rs"]
pub mod settings_county;
