[package]
name = "annactl"
version = "0.6.9"
edition = "2021"

[dependencies]
anna-rpc = { path = "../anna-rpc" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
time = { workspace = true }
dirs = { workspace = true }
toml = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
