//! Recipe System - Learned solutions for common tasks.
//!
//! Recipes allow Anna to:
//! - Store successful solutions for reuse
//! - Apply known solutions without LLM overhead
//! - Learn from wiki, LLM, and user corrections
//!
//! Recipe matching considers:
//! - Question patterns (fuzzy matching)
//! - System context (profile fields)
//! - Success history

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use crate::config::anna_data_dir;

/// A recipe for solving a specific type of problem
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recipe {
    /// Unique identifier
    pub id: String,

    /// Human-readable name
    pub name: String,

    /// Keywords that trigger this recipe (fuzzy matched)
    pub keywords: Vec<String>,

    /// Question patterns this recipe applies to
    pub patterns: Vec<String>,

    /// Required context - profile fields that must match
    /// e.g., {"editor": "vim"} means only apply if user has vim
    pub context: RecipeContext,

    /// Commands to execute (in order)
    pub commands: Vec<RecipeCommand>,

    /// How to verify the solution worked
    pub verification: Option<VerificationStep>,

    /// Where this recipe came from
    pub source: RecipeSource,

    /// How many times this recipe has been used successfully
    pub success_count: u32,

    /// When this recipe was last used
    pub last_used: Option<String>,

    /// Whether this recipe is enabled
    pub enabled: bool,
}

/// Context requirements for a recipe
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RecipeContext {
    /// Required OS (e.g., "Arch Linux")
    pub os: Option<String>,

    /// Required editor (e.g., "vim", "nvim")
    pub editor: Option<String>,

    /// Required shell (e.g., "bash", "zsh")
    pub shell: Option<String>,

    /// Required bootloader (e.g., "systemd-boot", "grub")
    pub bootloader: Option<String>,

    /// Required desktop environment
    pub desktop: Option<String>,

    /// Required display server (e.g., "wayland", "x11")
    pub display_server: Option<String>,

    /// Required filesystem (e.g., "btrfs", "ext4")
    pub filesystem: Option<String>,
}

/// A command in a recipe
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecipeCommand {
    /// The command to run
    pub command: String,

    /// Description of what this command does
    pub description: String,

    /// Whether this command modifies the system
    pub modifies_system: bool,

    /// File to backup before running (if modifies_system)
    pub backup_file: Option<String>,

    /// Whether to run as root (sudo)
    pub needs_root: bool,
}

/// How to verify a recipe worked
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationStep {
    /// Command to run to verify
    pub command: String,

    /// Expected output (substring match)
    pub expected_contains: Option<String>,

    /// Output should NOT contain this
    pub expected_not_contains: Option<String>,
}

/// Where a recipe came from
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RecipeSource {
    /// Built-in basic recipe
    BuiltIn,
    /// Extracted from Arch Wiki
    Wiki { article: String },
    /// Generated by LLM
    Llm { model: String },
    /// Provided by user
    User,
}

/// Recipe storage
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RecipeBook {
    /// All recipes
    pub recipes: Vec<Recipe>,

    /// When the recipe book was last updated
    pub last_updated: Option<String>,
}

impl RecipeBook {
    /// Load recipe book from disk
    pub fn load() -> Result<Self> {
        let path = recipes_path();
        if path.exists() {
            let content = std::fs::read_to_string(&path)?;
            let book: RecipeBook = serde_json::from_str(&content)?;
            Ok(book)
        } else {
            // Create with built-in recipes
            let mut book = RecipeBook::default();
            book.add_builtin_recipes();
            book.save()?;
            Ok(book)
        }
    }

    /// Save recipe book to disk
    pub fn save(&self) -> Result<()> {
        let path = recipes_path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let json = serde_json::to_string_pretty(self)?;
        std::fs::write(path, json)?;
        Ok(())
    }

    /// Add built-in recipes
    fn add_builtin_recipes(&mut self) {
        // Recipe: Enable vim syntax highlighting
        self.recipes.push(Recipe {
            id: "vim-syntax-highlighting".to_string(),
            name: "Enable Vim Syntax Highlighting".to_string(),
            keywords: vec![
                "vim".to_string(),
                "syntax".to_string(),
                "highlighting".to_string(),
                "color".to_string(),
            ],
            patterns: vec![
                "enable vim syntax highlighting".to_string(),
                "turn on vim syntax".to_string(),
                "vim colors".to_string(),
                "syntax highlighting vim".to_string(),
            ],
            context: RecipeContext {
                editor: Some("vim".to_string()),
                ..Default::default()
            },
            commands: vec![
                RecipeCommand {
                    command: "grep -q 'syntax on' ~/.vimrc 2>/dev/null || echo 'syntax on' >> ~/.vimrc".to_string(),
                    description: "Enable syntax highlighting in .vimrc".to_string(),
                    modifies_system: true,
                    backup_file: Some("~/.vimrc".to_string()),
                    needs_root: false,
                },
            ],
            verification: Some(VerificationStep {
                command: "grep 'syntax on' ~/.vimrc".to_string(),
                expected_contains: Some("syntax on".to_string()),
                expected_not_contains: None,
            }),
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: Enable nvim syntax highlighting
        self.recipes.push(Recipe {
            id: "nvim-syntax-highlighting".to_string(),
            name: "Enable Neovim Syntax Highlighting".to_string(),
            keywords: vec![
                "nvim".to_string(),
                "neovim".to_string(),
                "syntax".to_string(),
                "highlighting".to_string(),
            ],
            patterns: vec![
                "enable neovim syntax highlighting".to_string(),
                "nvim syntax".to_string(),
                "neovim colors".to_string(),
            ],
            context: RecipeContext {
                editor: Some("nvim".to_string()),
                ..Default::default()
            },
            commands: vec![
                RecipeCommand {
                    command: "mkdir -p ~/.config/nvim && grep -q 'syntax on' ~/.config/nvim/init.vim 2>/dev/null || echo 'syntax on' >> ~/.config/nvim/init.vim".to_string(),
                    description: "Enable syntax highlighting in nvim config".to_string(),
                    modifies_system: true,
                    backup_file: Some("~/.config/nvim/init.vim".to_string()),
                    needs_root: false,
                },
            ],
            verification: Some(VerificationStep {
                command: "grep 'syntax on' ~/.config/nvim/init.vim".to_string(),
                expected_contains: Some("syntax on".to_string()),
                expected_not_contains: None,
            }),
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: Check disk usage
        self.recipes.push(Recipe {
            id: "disk-usage".to_string(),
            name: "Check Disk Usage".to_string(),
            keywords: vec![
                "disk".to_string(),
                "space".to_string(),
                "usage".to_string(),
                "storage".to_string(),
                "full".to_string(),
            ],
            patterns: vec![
                "disk usage".to_string(),
                "disk space".to_string(),
                "how much disk".to_string(),
                "storage space".to_string(),
                "disk full".to_string(),
            ],
            context: RecipeContext::default(),
            commands: vec![
                RecipeCommand {
                    command: "df -h".to_string(),
                    description: "Show disk usage in human-readable format".to_string(),
                    modifies_system: false,
                    backup_file: None,
                    needs_root: false,
                },
            ],
            verification: None,
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: Check memory usage
        self.recipes.push(Recipe {
            id: "memory-usage".to_string(),
            name: "Check Memory Usage".to_string(),
            keywords: vec![
                "memory".to_string(),
                "ram".to_string(),
                "usage".to_string(),
                "free".to_string(),
            ],
            patterns: vec![
                "memory usage".to_string(),
                "ram usage".to_string(),
                "how much memory".to_string(),
                "how much ram".to_string(),
                "free memory".to_string(),
            ],
            context: RecipeContext::default(),
            commands: vec![
                RecipeCommand {
                    command: "free -h".to_string(),
                    description: "Show memory usage in human-readable format".to_string(),
                    modifies_system: false,
                    backup_file: None,
                    needs_root: false,
                },
            ],
            verification: None,
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: Check CPU usage
        self.recipes.push(Recipe {
            id: "cpu-usage".to_string(),
            name: "Check CPU Usage".to_string(),
            keywords: vec![
                "cpu".to_string(),
                "processor".to_string(),
                "usage".to_string(),
                "load".to_string(),
            ],
            patterns: vec![
                "cpu usage".to_string(),
                "what is using cpu".to_string(),
                "high cpu".to_string(),
                "cpu load".to_string(),
            ],
            context: RecipeContext::default(),
            commands: vec![
                RecipeCommand {
                    command: "ps aux --sort=-%cpu | head -10".to_string(),
                    description: "Show top CPU-consuming processes".to_string(),
                    modifies_system: false,
                    backup_file: None,
                    needs_root: false,
                },
            ],
            verification: None,
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: Check kernel version
        self.recipes.push(Recipe {
            id: "kernel-version".to_string(),
            name: "Check Kernel Version".to_string(),
            keywords: vec![
                "kernel".to_string(),
                "version".to_string(),
                "linux".to_string(),
            ],
            patterns: vec![
                "kernel version".to_string(),
                "what kernel".to_string(),
                "linux version".to_string(),
            ],
            context: RecipeContext::default(),
            commands: vec![
                RecipeCommand {
                    command: "uname -r".to_string(),
                    description: "Show kernel version".to_string(),
                    modifies_system: false,
                    backup_file: None,
                    needs_root: false,
                },
            ],
            verification: None,
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: Update system (pacman)
        self.recipes.push(Recipe {
            id: "update-system-pacman".to_string(),
            name: "Update System with Pacman".to_string(),
            keywords: vec![
                "update".to_string(),
                "upgrade".to_string(),
                "pacman".to_string(),
                "system".to_string(),
            ],
            patterns: vec![
                "update system".to_string(),
                "upgrade system".to_string(),
                "update packages".to_string(),
                "pacman update".to_string(),
            ],
            context: RecipeContext {
                os: Some("Arch Linux".to_string()),
                ..Default::default()
            },
            commands: vec![
                RecipeCommand {
                    command: "pacman -Syu --noconfirm".to_string(),
                    description: "Update all packages".to_string(),
                    modifies_system: true,
                    backup_file: None,
                    needs_root: true,
                },
            ],
            verification: None,
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });

        // Recipe: List failing services
        self.recipes.push(Recipe {
            id: "failing-services".to_string(),
            name: "Check Failing Services".to_string(),
            keywords: vec![
                "service".to_string(),
                "systemd".to_string(),
                "failing".to_string(),
                "failed".to_string(),
            ],
            patterns: vec![
                "failing services".to_string(),
                "failed services".to_string(),
                "what services".to_string(),
                "systemd failed".to_string(),
            ],
            context: RecipeContext::default(),
            commands: vec![
                RecipeCommand {
                    command: "systemctl --failed".to_string(),
                    description: "List failed systemd services".to_string(),
                    modifies_system: false,
                    backup_file: None,
                    needs_root: false,
                },
            ],
            verification: None,
            source: RecipeSource::BuiltIn,
            success_count: 0,
            last_used: None,
            enabled: true,
        });
    }

    /// Find matching recipes for a question
    pub fn find_matches(&self, question: &str, context: &crate::profile::SystemInfo) -> Vec<&Recipe> {
        let question_lower = question.to_lowercase();
        let words: Vec<&str> = question_lower.split_whitespace().collect();

        let mut matches: Vec<(&Recipe, f32)> = self.recipes
            .iter()
            .filter(|r| r.enabled)
            .filter_map(|recipe| {
                // Check context requirements
                if !recipe_context_matches(&recipe.context, context) {
                    return None;
                }

                // Calculate match score
                let score = calculate_match_score(recipe, &question_lower, &words);
                if score > 0.3 {
                    Some((recipe, score))
                } else {
                    None
                }
            })
            .collect();

        // Sort by score (highest first)
        matches.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

        matches.into_iter().map(|(r, _)| r).collect()
    }

    /// Add a new recipe
    pub fn add_recipe(&mut self, recipe: Recipe) {
        self.recipes.push(recipe);
        self.last_updated = Some(chrono::Utc::now().to_rfc3339());
    }

    /// Mark a recipe as used successfully
    pub fn mark_success(&mut self, recipe_id: &str) {
        if let Some(recipe) = self.recipes.iter_mut().find(|r| r.id == recipe_id) {
            recipe.success_count += 1;
            recipe.last_used = Some(chrono::Utc::now().to_rfc3339());
        }
    }
}

/// Check if recipe context matches system context
fn recipe_context_matches(recipe_ctx: &RecipeContext, system: &crate::profile::SystemInfo) -> bool {
    // OS check
    if let Some(ref required_os) = recipe_ctx.os {
        if let Some(ref system_os) = system.os_name {
            if !system_os.to_lowercase().contains(&required_os.to_lowercase()) {
                return false;
            }
        }
    }

    // Editor check
    if let Some(ref required_editor) = recipe_ctx.editor {
        if let Some(ref system_editor) = system.editor {
            if system_editor != required_editor {
                return false;
            }
        } else {
            return false; // No editor detected, but recipe requires one
        }
    }

    // Shell check
    if let Some(ref required_shell) = recipe_ctx.shell {
        if let Some(ref system_shell) = system.shell {
            if system_shell != required_shell {
                return false;
            }
        }
    }

    // Bootloader check
    if let Some(ref required_boot) = recipe_ctx.bootloader {
        if let Some(ref system_boot) = system.bootloader {
            if system_boot != required_boot {
                return false;
            }
        }
    }

    // Desktop check
    if let Some(ref required_de) = recipe_ctx.desktop {
        if let Some(ref system_de) = system.desktop {
            if !system_de.to_lowercase().contains(&required_de.to_lowercase()) {
                return false;
            }
        }
    }

    // Filesystem check
    if let Some(ref required_fs) = recipe_ctx.filesystem {
        if let Some(ref system_fs) = system.root_filesystem {
            if system_fs != required_fs {
                return false;
            }
        }
    }

    true
}

/// Calculate match score for a recipe
fn calculate_match_score(recipe: &Recipe, question: &str, words: &[&str]) -> f32 {
    let mut score = 0.0;

    // Check pattern matches
    for pattern in &recipe.patterns {
        if question.contains(pattern) {
            score += 0.5;
        }
    }

    // Check keyword matches
    let keyword_matches = recipe.keywords.iter()
        .filter(|k| words.iter().any(|w| w.contains(k.as_str())))
        .count();

    if !recipe.keywords.is_empty() {
        score += (keyword_matches as f32) / (recipe.keywords.len() as f32) * 0.3;
    }

    // Boost by success count (max 0.2 boost)
    let success_boost = (recipe.success_count as f32 / 10.0).min(0.2);
    score += success_boost;

    score
}

/// Get recipes storage path
pub fn recipes_path() -> PathBuf {
    anna_data_dir().join("recipes.json")
}
