//! Recipe types - data structures for the recipe system.

use serde::{Deserialize, Serialize};

/// A recipe for solving a specific type of problem
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recipe {
    /// Unique identifier
    pub id: String,

    /// Human-readable name
    pub name: String,

    /// Keywords that trigger this recipe (fuzzy matched)
    pub keywords: Vec<String>,

    /// Question patterns this recipe applies to
    pub patterns: Vec<String>,

    /// Required context - profile fields that must match
    /// e.g., {"editor": "vim"} means only apply if user has vim
    pub context: RecipeContext,

    /// Commands to execute (in order)
    pub commands: Vec<RecipeCommand>,

    /// How to verify the solution worked
    pub verification: Option<VerificationStep>,

    /// Where this recipe came from
    pub source: RecipeSource,

    /// How many times this recipe has been used successfully
    pub success_count: u32,

    /// When this recipe was last used
    pub last_used: Option<String>,

    /// Whether this recipe is enabled
    pub enabled: bool,
}

/// Context requirements for a recipe
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RecipeContext {
    /// Required OS (e.g., "Arch Linux")
    pub os: Option<String>,

    /// Required editor (e.g., "vim", "nvim")
    pub editor: Option<String>,

    /// Required shell (e.g., "bash", "zsh")
    pub shell: Option<String>,

    /// Required bootloader (e.g., "systemd-boot", "grub")
    pub bootloader: Option<String>,

    /// Required desktop environment
    pub desktop: Option<String>,

    /// Required display server (e.g., "wayland", "x11")
    pub display_server: Option<String>,

    /// Required filesystem (e.g., "btrfs", "ext4")
    pub filesystem: Option<String>,
}

/// A command in a recipe
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecipeCommand {
    /// The command to run
    pub command: String,

    /// Description of what this command does
    pub description: String,

    /// Whether this command modifies the system
    pub modifies_system: bool,

    /// File to backup before running (if modifies_system)
    pub backup_file: Option<String>,

    /// Whether to run as root (sudo)
    pub needs_root: bool,
}

/// How to verify a recipe worked
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationStep {
    /// Command to run to verify
    pub command: String,

    /// Expected output (substring match)
    pub expected_contains: Option<String>,

    /// Output should NOT contain this
    pub expected_not_contains: Option<String>,
}

/// Where a recipe came from
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecipeSource {
    /// Built-in basic recipe
    BuiltIn,
    /// Extracted from Arch Wiki
    Wiki { article: String },
    /// Generated by LLM
    Llm { model: String },
    /// Provided by user
    User,
    /// v0.3.14: Learned from successful experiences
    Learned,
}

/// Recipe storage
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RecipeBook {
    /// All recipes
    pub recipes: Vec<Recipe>,

    /// When the recipe book was last updated
    pub last_updated: Option<String>,
}
